spring:
  application:
    name: authservices
  datasource:
    url: jdbc:postgresql://localhost:5432/authservices
    username: postgres
    password: dontwastetime
    driver-class-name: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        "[format_sql]": true
        "[use_sql_comments]": true
  data:
    redis:
      host: localhost
      port: 6379
      password:
      database: 0
logging:
  level:
    "[org.springframework.security]": DEBUG
jwt:
  secret: 63iPoQhsvC+H6+Oz9WSDp0ePZZllx+7Y/e3Dnz1MEKsvCD43CByhuCg/zQ7sbz9b
  expiration: 3600000
  refresh-expiration: 7200000
