spring:
  application:
    name: authservices
  datasource:
    url: jdbc:postgresql://localhost:5432/authservices
    username: postgres
    password: dontwastetime
    driver-class-name: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        "[format_sql]": true
        "[use_sql_comments]": true
  session:
    timeout: 15m
    redis:
      cleanup-cron: 0 * * * * *
      flush-mode: on_save

  data:
    redis:
      host: localhost
      port: 6379
      password:

server:
  servlet:
    session:
      cookie:
        name: JSESSIONID
        same-site: strict
        domain: localhost
        path: /
        http-only: true
        secure: false
logging:
  level:
    "[org.springframework.security]": DEBUG

custom:
  max:
    session: 1